spring:
  profiles:
    active: local
    group:
      local: local, common, secret

---
spring:
  config:
    activate:
      on-profile: local

---
pring:
  config:
    activate:
      on-profile: common

mybatis:
  mapper-locations:
    - /mappers/*.xml
